# Generated by Django 5.0.4 on 2025-05-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='This is default content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
